language: cpp
sudo: false
dist: trusty
compiler:
  - gcc
  - clang
jdk:
  - openjdk7
before_script:
  - mkdir build
  - cd build
  - cmake ..
env:
  - MAVEN_OPTS=-Xmx2g MAVEN_SKIP_RC=true
script:
  - make package test-out
